from _typeshed import Incomplete
from swimlane.exceptions import InvalidSwimlaneBuildVersion as InvalidSwimlaneBuildVersion

def compare_versions(version_a, version_b, zerofill: bool = ...): ...
def requires_swimlane_version(min_version: Incomplete | None = ..., max_version: Incomplete | None = ...): ...
def get_package_version(): ...
