"""
    Fingoti API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import fingoti
from fingoti.model.device_version import DeviceVersion


class TestDeviceVersion(unittest.TestCase):
    """DeviceVersion unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDeviceVersion(self):
        """Test DeviceVersion"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DeviceVersion()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
