"""
    Fingoti API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import fingoti
from fingoti.model.regiser_organisation_dto import RegiserOrganisationDto


class TestRegiserOrganisationDto(unittest.TestCase):
    """RegiserOrganisationDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRegiserOrganisationDto(self):
        """Test RegiserOrganisationDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RegiserOrganisationDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
