"""
    Fingoti API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import fingoti
from fingoti.model.webhook_retry import WebhookRetry
globals()['WebhookRetry'] = WebhookRetry
from fingoti.model.webhook_retry_request import WebhookRetryRequest


class TestWebhookRetryRequest(unittest.TestCase):
    """WebhookRetryRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWebhookRetryRequest(self):
        """Test WebhookRetryRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = WebhookRetryRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
