"""
    Fingoti API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import fingoti
from fingoti.model.organisation_tenant_dto import OrganisationTenantDto


class TestOrganisationTenantDto(unittest.TestCase):
    """OrganisationTenantDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOrganisationTenantDto(self):
        """Test OrganisationTenantDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OrganisationTenantDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
