"""
    Fingoti API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import fingoti
from fingoti.model.organisation_presets_dto import OrganisationPresetsDto
globals()['OrganisationPresetsDto'] = OrganisationPresetsDto
from fingoti.model.organisation_preset_response import OrganisationPresetResponse


class TestOrganisationPresetResponse(unittest.TestCase):
    """OrganisationPresetResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOrganisationPresetResponse(self):
        """Test OrganisationPresetResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OrganisationPresetResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
