"""
    Fingoti API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import fingoti
from fingoti.model.device_support import DeviceSupport


class TestDeviceSupport(unittest.TestCase):
    """DeviceSupport unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDeviceSupport(self):
        """Test DeviceSupport"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DeviceSupport()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
