"""
    Fingoti API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import fingoti
from fingoti.model.partner_contact import PartnerContact


class TestPartnerContact(unittest.TestCase):
    """PartnerContact unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPartnerContact(self):
        """Test PartnerContact"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PartnerContact()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
