"""
    Fingoti API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import fingoti
from fingoti.model.all_webhooks_dto import AllWebhooksDto
globals()['AllWebhooksDto'] = AllWebhooksDto
from fingoti.model.engine_webhooks_response import EngineWebhooksResponse


class TestEngineWebhooksResponse(unittest.TestCase):
    """EngineWebhooksResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEngineWebhooksResponse(self):
        """Test EngineWebhooksResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EngineWebhooksResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
