"""
    Fingoti API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import fingoti
from fingoti.model.webhook_headers import WebhookHeaders
globals()['WebhookHeaders'] = WebhookHeaders
from fingoti.model.add_webhook_dto import AddWebhookDto


class TestAddWebhookDto(unittest.TestCase):
    """AddWebhookDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAddWebhookDto(self):
        """Test AddWebhookDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AddWebhookDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
