"""
    Delphix DCT API

    Delphix DCT API  # noqa: E501

    The version of the OpenAPI document: 2.4.0
    Contact: support@delphix.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import delphix.api.gateway
from delphix.api.gateway.model.effective_policy import EffectivePolicy


class TestEffectivePolicy(unittest.TestCase):
    """EffectivePolicy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEffectivePolicy(self):
        """Test EffectivePolicy"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EffectivePolicy()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
