from swimlane.core.resolver import SwimlaneResolver as SwimlaneResolver
from swimlane.core.resources.app import App
from swimlane.core.resources.report import Report as Report
from swimlane.core.resources.report import report_factory as report_factory

class ReportAdapter(SwimlaneResolver):
    def __init__(self, app: App) -> None: ...
    def list(self): ...
    def get(self, report_id: str): ...
    def build(self, name: str, **kwargs): ...
