from .base import MultiSelectField as MultiSelectField
from _typeshed import Incomplete
from swimlane.core.resources.usergroup import User as User, UserGroup as UserGroup
from swimlane.exceptions import ValidationError as ValidationError

class UserGroupField(MultiSelectField):
    field_type: Incomplete
    supported_types: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def validate_value(self, value) -> None: ...
    def get_batch_representation(self): ...
    def set_swimlane(self, value): ...
    def cast_to_python(self, value): ...
    def cast_to_swimlane(self, value): ...
