VERSION_YEAR = 2023
VERSION_MONTH = int('01')
VERSION_DAY = int('19')
VERSION_HOUR = int('11')
VERSION_MINUTE = int('11')
MAJOR_VERSION = 0
MINOR_VERSION = 24
PATCH_VERSION = 202301191111
version_date = '2023/01/19 11:11'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
