
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-18T18:19:49-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "4d1f04ca0128935edaaff9f59c1445a8e943daca",
 "version": "4.7.45"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
