# coding: utf-8

"""
    Fingoti API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from fingoti.configuration import Configuration


class OrganisationTenantDto(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'str',
        'organisation_number': 'str',
        'organisation_name': 'str',
        'subscription_id': 'str',
        'is_business': 'bool',
        'trial_used': 'bool',
        'disabled': 'bool'
    }

    attribute_map = {
        'id': 'id',
        'organisation_number': 'organisationNumber',
        'organisation_name': 'organisationName',
        'subscription_id': 'subscriptionId',
        'is_business': 'isBusiness',
        'trial_used': 'trialUsed',
        'disabled': 'disabled'
    }

    def __init__(self, id=None, organisation_number=None, organisation_name=None, subscription_id=None, is_business=None, trial_used=None, disabled=None, local_vars_configuration=None):  # noqa: E501
        """OrganisationTenantDto - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._organisation_number = None
        self._organisation_name = None
        self._subscription_id = None
        self._is_business = None
        self._trial_used = None
        self._disabled = None
        self.discriminator = None

        if id is not None:
            self.id = id
        self.organisation_number = organisation_number
        self.organisation_name = organisation_name
        self.subscription_id = subscription_id
        if is_business is not None:
            self.is_business = is_business
        if trial_used is not None:
            self.trial_used = trial_used
        if disabled is not None:
            self.disabled = disabled

    @property
    def id(self):
        """Gets the id of this OrganisationTenantDto.  # noqa: E501


        :return: The id of this OrganisationTenantDto.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this OrganisationTenantDto.


        :param id: The id of this OrganisationTenantDto.  # noqa: E501
        :type id: str
        """

        self._id = id

    @property
    def organisation_number(self):
        """Gets the organisation_number of this OrganisationTenantDto.  # noqa: E501


        :return: The organisation_number of this OrganisationTenantDto.  # noqa: E501
        :rtype: str
        """
        return self._organisation_number

    @organisation_number.setter
    def organisation_number(self, organisation_number):
        """Sets the organisation_number of this OrganisationTenantDto.


        :param organisation_number: The organisation_number of this OrganisationTenantDto.  # noqa: E501
        :type organisation_number: str
        """

        self._organisation_number = organisation_number

    @property
    def organisation_name(self):
        """Gets the organisation_name of this OrganisationTenantDto.  # noqa: E501


        :return: The organisation_name of this OrganisationTenantDto.  # noqa: E501
        :rtype: str
        """
        return self._organisation_name

    @organisation_name.setter
    def organisation_name(self, organisation_name):
        """Sets the organisation_name of this OrganisationTenantDto.


        :param organisation_name: The organisation_name of this OrganisationTenantDto.  # noqa: E501
        :type organisation_name: str
        """

        self._organisation_name = organisation_name

    @property
    def subscription_id(self):
        """Gets the subscription_id of this OrganisationTenantDto.  # noqa: E501


        :return: The subscription_id of this OrganisationTenantDto.  # noqa: E501
        :rtype: str
        """
        return self._subscription_id

    @subscription_id.setter
    def subscription_id(self, subscription_id):
        """Sets the subscription_id of this OrganisationTenantDto.


        :param subscription_id: The subscription_id of this OrganisationTenantDto.  # noqa: E501
        :type subscription_id: str
        """

        self._subscription_id = subscription_id

    @property
    def is_business(self):
        """Gets the is_business of this OrganisationTenantDto.  # noqa: E501


        :return: The is_business of this OrganisationTenantDto.  # noqa: E501
        :rtype: bool
        """
        return self._is_business

    @is_business.setter
    def is_business(self, is_business):
        """Sets the is_business of this OrganisationTenantDto.


        :param is_business: The is_business of this OrganisationTenantDto.  # noqa: E501
        :type is_business: bool
        """

        self._is_business = is_business

    @property
    def trial_used(self):
        """Gets the trial_used of this OrganisationTenantDto.  # noqa: E501


        :return: The trial_used of this OrganisationTenantDto.  # noqa: E501
        :rtype: bool
        """
        return self._trial_used

    @trial_used.setter
    def trial_used(self, trial_used):
        """Sets the trial_used of this OrganisationTenantDto.


        :param trial_used: The trial_used of this OrganisationTenantDto.  # noqa: E501
        :type trial_used: bool
        """

        self._trial_used = trial_used

    @property
    def disabled(self):
        """Gets the disabled of this OrganisationTenantDto.  # noqa: E501


        :return: The disabled of this OrganisationTenantDto.  # noqa: E501
        :rtype: bool
        """
        return self._disabled

    @disabled.setter
    def disabled(self, disabled):
        """Sets the disabled of this OrganisationTenantDto.


        :param disabled: The disabled of this OrganisationTenantDto.  # noqa: E501
        :type disabled: bool
        """

        self._disabled = disabled

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OrganisationTenantDto):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, OrganisationTenantDto):
            return True

        return self.to_dict() != other.to_dict()
