# coding: utf-8

"""
    Fingoti API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from fingoti.configuration import Configuration


class TimerRequest(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        '_property': 'str',
        'operation': 'RequestOperation',
        'payload': 'object'
    }

    attribute_map = {
        '_property': 'property',
        'operation': 'operation',
        'payload': 'payload'
    }

    def __init__(self, _property=None, operation=None, payload=None, local_vars_configuration=None):  # noqa: E501
        """TimerRequest - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self.__property = None
        self._operation = None
        self._payload = None
        self.discriminator = None

        self._property = _property
        if operation is not None:
            self.operation = operation
        self.payload = payload

    @property
    def _property(self):
        """Gets the _property of this TimerRequest.  # noqa: E501


        :return: The _property of this TimerRequest.  # noqa: E501
        :rtype: str
        """
        return self.__property

    @_property.setter
    def _property(self, _property):
        """Sets the _property of this TimerRequest.


        :param _property: The _property of this TimerRequest.  # noqa: E501
        :type _property: str
        """

        self.__property = _property

    @property
    def operation(self):
        """Gets the operation of this TimerRequest.  # noqa: E501


        :return: The operation of this TimerRequest.  # noqa: E501
        :rtype: RequestOperation
        """
        return self._operation

    @operation.setter
    def operation(self, operation):
        """Sets the operation of this TimerRequest.


        :param operation: The operation of this TimerRequest.  # noqa: E501
        :type operation: RequestOperation
        """

        self._operation = operation

    @property
    def payload(self):
        """Gets the payload of this TimerRequest.  # noqa: E501


        :return: The payload of this TimerRequest.  # noqa: E501
        :rtype: object
        """
        return self._payload

    @payload.setter
    def payload(self, payload):
        """Sets the payload of this TimerRequest.


        :param payload: The payload of this TimerRequest.  # noqa: E501
        :type payload: object
        """

        self._payload = payload

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TimerRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, TimerRequest):
            return True

        return self.to_dict() != other.to_dict()
