# coding: utf-8

"""
    Fingoti API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from fingoti.configuration import Configuration


class TokenSuccessResponse(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'success': 'bool',
        'message': 'str',
        'id': 'str',
        'name': 'str',
        'key': 'str',
        'enabled': 'bool',
        'expiry': 'str'
    }

    attribute_map = {
        'success': 'success',
        'message': 'message',
        'id': 'id',
        'name': 'name',
        'key': 'key',
        'enabled': 'enabled',
        'expiry': 'expiry'
    }

    def __init__(self, success=None, message=None, id=None, name=None, key=None, enabled=None, expiry=None, local_vars_configuration=None):  # noqa: E501
        """TokenSuccessResponse - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._success = None
        self._message = None
        self._id = None
        self._name = None
        self._key = None
        self._enabled = None
        self._expiry = None
        self.discriminator = None

        if success is not None:
            self.success = success
        self.message = message
        if id is not None:
            self.id = id
        self.name = name
        self.key = key
        if enabled is not None:
            self.enabled = enabled
        self.expiry = expiry

    @property
    def success(self):
        """Gets the success of this TokenSuccessResponse.  # noqa: E501


        :return: The success of this TokenSuccessResponse.  # noqa: E501
        :rtype: bool
        """
        return self._success

    @success.setter
    def success(self, success):
        """Sets the success of this TokenSuccessResponse.


        :param success: The success of this TokenSuccessResponse.  # noqa: E501
        :type success: bool
        """

        self._success = success

    @property
    def message(self):
        """Gets the message of this TokenSuccessResponse.  # noqa: E501


        :return: The message of this TokenSuccessResponse.  # noqa: E501
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this TokenSuccessResponse.


        :param message: The message of this TokenSuccessResponse.  # noqa: E501
        :type message: str
        """

        self._message = message

    @property
    def id(self):
        """Gets the id of this TokenSuccessResponse.  # noqa: E501


        :return: The id of this TokenSuccessResponse.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this TokenSuccessResponse.


        :param id: The id of this TokenSuccessResponse.  # noqa: E501
        :type id: str
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this TokenSuccessResponse.  # noqa: E501


        :return: The name of this TokenSuccessResponse.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this TokenSuccessResponse.


        :param name: The name of this TokenSuccessResponse.  # noqa: E501
        :type name: str
        """

        self._name = name

    @property
    def key(self):
        """Gets the key of this TokenSuccessResponse.  # noqa: E501


        :return: The key of this TokenSuccessResponse.  # noqa: E501
        :rtype: str
        """
        return self._key

    @key.setter
    def key(self, key):
        """Sets the key of this TokenSuccessResponse.


        :param key: The key of this TokenSuccessResponse.  # noqa: E501
        :type key: str
        """

        self._key = key

    @property
    def enabled(self):
        """Gets the enabled of this TokenSuccessResponse.  # noqa: E501


        :return: The enabled of this TokenSuccessResponse.  # noqa: E501
        :rtype: bool
        """
        return self._enabled

    @enabled.setter
    def enabled(self, enabled):
        """Sets the enabled of this TokenSuccessResponse.


        :param enabled: The enabled of this TokenSuccessResponse.  # noqa: E501
        :type enabled: bool
        """

        self._enabled = enabled

    @property
    def expiry(self):
        """Gets the expiry of this TokenSuccessResponse.  # noqa: E501


        :return: The expiry of this TokenSuccessResponse.  # noqa: E501
        :rtype: str
        """
        return self._expiry

    @expiry.setter
    def expiry(self, expiry):
        """Sets the expiry of this TokenSuccessResponse.


        :param expiry: The expiry of this TokenSuccessResponse.  # noqa: E501
        :type expiry: str
        """

        self._expiry = expiry

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TokenSuccessResponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, TokenSuccessResponse):
            return True

        return self.to_dict() != other.to_dict()
