# coding: utf-8

"""


    Generated by: https://openapi-generator.tech
"""

import unittest
from unittest.mock import patch

import urllib3

import vrt_lss_account
from vrt_lss_account.paths.account_report import get  # noqa: E501
from vrt_lss_account import configuration, schemas, api_client

from .. import ApiTestMixin


class TestAccountReport(ApiTestMixin, unittest.TestCase):
    """
    AccountReport unit test stubs
        Report creating  # noqa: E501
    """
    _configuration = configuration.Configuration()

    def setUp(self):
        used_api_client = api_client.ApiClient(configuration=self._configuration)
        self.api = get.ApiForget(api_client=used_api_client)  # noqa: E501

    def tearDown(self):
        pass

    response_status = 200




if __name__ == '__main__':
    unittest.main()
