
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-17T18:55:17+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "ba4c2d5e0a448bc2fa2f3c5dab5e5ee6589b7c8b",
 "version": "0.2.60.post0.dev31"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
