VERSION_YEAR = 2023
VERSION_MONTH = int('01')
VERSION_DAY = int('15')
VERSION_HOUR = int('07')
VERSION_MINUTE = int('49')
MAJOR_VERSION = 0
MINOR_VERSION = 1
PATCH_VERSION = 202301150749
version_date = '2023/01/15 07:49'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
