"""
    Delphix DCT API

    Delphix DCT API  # noqa: E501

    The version of the OpenAPI document: 2.4.0
    Contact: support@delphix.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import delphix.api.gateway
from delphix.api.gateway.model.scoped_object_item import ScopedObjectItem
from delphix.api.gateway.model.tag import Tag
globals()['ScopedObjectItem'] = ScopedObjectItem
globals()['Tag'] = Tag
from delphix.api.gateway.model.access_group_policy import AccessGroupPolicy


class TestAccessGroupPolicy(unittest.TestCase):
    """AccessGroupPolicy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccessGroupPolicy(self):
        """Test AccessGroupPolicy"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AccessGroupPolicy()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
