# coding: utf-8

"""
    GeoAPI

    Geospatial API for TAPIS  # noqa: E501

    OpenAPI spec version: 0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from geoapi_client.configuration import Configuration


class Streetview(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'instances': 'list[StreetviewInstance]',
        'organizations': 'list[StreetviewOrganization]',
        'service': 'str',
        'service_user': 'str',
        'token': 'str',
        'user_id': 'int'
    }

    attribute_map = {
        'id': 'id',
        'instances': 'instances',
        'organizations': 'organizations',
        'service': 'service',
        'service_user': 'service_user',
        'token': 'token',
        'user_id': 'user_id'
    }

    def __init__(self, id=None, instances=None, organizations=None, service=None, service_user=None, token=None, user_id=None, _configuration=None):  # noqa: E501
        """Streetview - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._id = None
        self._instances = None
        self._organizations = None
        self._service = None
        self._service_user = None
        self._token = None
        self._user_id = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if instances is not None:
            self.instances = instances
        if organizations is not None:
            self.organizations = organizations
        if service is not None:
            self.service = service
        if service_user is not None:
            self.service_user = service_user
        if token is not None:
            self.token = token
        if user_id is not None:
            self.user_id = user_id

    @property
    def id(self):
        """Gets the id of this Streetview.  # noqa: E501


        :return: The id of this Streetview.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Streetview.


        :param id: The id of this Streetview.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def instances(self):
        """Gets the instances of this Streetview.  # noqa: E501


        :return: The instances of this Streetview.  # noqa: E501
        :rtype: list[StreetviewInstance]
        """
        return self._instances

    @instances.setter
    def instances(self, instances):
        """Sets the instances of this Streetview.


        :param instances: The instances of this Streetview.  # noqa: E501
        :type: list[StreetviewInstance]
        """

        self._instances = instances

    @property
    def organizations(self):
        """Gets the organizations of this Streetview.  # noqa: E501


        :return: The organizations of this Streetview.  # noqa: E501
        :rtype: list[StreetviewOrganization]
        """
        return self._organizations

    @organizations.setter
    def organizations(self, organizations):
        """Sets the organizations of this Streetview.


        :param organizations: The organizations of this Streetview.  # noqa: E501
        :type: list[StreetviewOrganization]
        """

        self._organizations = organizations

    @property
    def service(self):
        """Gets the service of this Streetview.  # noqa: E501


        :return: The service of this Streetview.  # noqa: E501
        :rtype: str
        """
        return self._service

    @service.setter
    def service(self, service):
        """Sets the service of this Streetview.


        :param service: The service of this Streetview.  # noqa: E501
        :type: str
        """

        self._service = service

    @property
    def service_user(self):
        """Gets the service_user of this Streetview.  # noqa: E501


        :return: The service_user of this Streetview.  # noqa: E501
        :rtype: str
        """
        return self._service_user

    @service_user.setter
    def service_user(self, service_user):
        """Sets the service_user of this Streetview.


        :param service_user: The service_user of this Streetview.  # noqa: E501
        :type: str
        """

        self._service_user = service_user

    @property
    def token(self):
        """Gets the token of this Streetview.  # noqa: E501


        :return: The token of this Streetview.  # noqa: E501
        :rtype: str
        """
        return self._token

    @token.setter
    def token(self, token):
        """Sets the token of this Streetview.


        :param token: The token of this Streetview.  # noqa: E501
        :type: str
        """

        self._token = token

    @property
    def user_id(self):
        """Gets the user_id of this Streetview.  # noqa: E501


        :return: The user_id of this Streetview.  # noqa: E501
        :rtype: int
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this Streetview.


        :param user_id: The user_id of this Streetview.  # noqa: E501
        :type: int
        """

        self._user_id = user_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Streetview, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Streetview):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Streetview):
            return True

        return self.to_dict() != other.to_dict()
