# coding: utf-8

"""
    GeoAPI

    Geospatial API for TAPIS  # noqa: E501

    OpenAPI spec version: 0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from geoapi_client.configuration import Configuration


class TileServer(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'attribution': 'str',
        'id': 'int',
        'name': 'str',
        'tile_options': 'object',
        'type': 'str',
        'ui_options': 'object',
        'url': 'str'
    }

    attribute_map = {
        'attribution': 'attribution',
        'id': 'id',
        'name': 'name',
        'tile_options': 'tileOptions',
        'type': 'type',
        'ui_options': 'uiOptions',
        'url': 'url'
    }

    def __init__(self, attribution=None, id=None, name=None, tile_options=None, type=None, ui_options=None, url=None, _configuration=None):  # noqa: E501
        """TileServer - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._attribution = None
        self._id = None
        self._name = None
        self._tile_options = None
        self._type = None
        self._ui_options = None
        self._url = None
        self.discriminator = None

        if attribution is not None:
            self.attribution = attribution
        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if tile_options is not None:
            self.tile_options = tile_options
        if type is not None:
            self.type = type
        if ui_options is not None:
            self.ui_options = ui_options
        if url is not None:
            self.url = url

    @property
    def attribution(self):
        """Gets the attribution of this TileServer.  # noqa: E501


        :return: The attribution of this TileServer.  # noqa: E501
        :rtype: str
        """
        return self._attribution

    @attribution.setter
    def attribution(self, attribution):
        """Sets the attribution of this TileServer.


        :param attribution: The attribution of this TileServer.  # noqa: E501
        :type: str
        """

        self._attribution = attribution

    @property
    def id(self):
        """Gets the id of this TileServer.  # noqa: E501


        :return: The id of this TileServer.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this TileServer.


        :param id: The id of this TileServer.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this TileServer.  # noqa: E501


        :return: The name of this TileServer.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this TileServer.


        :param name: The name of this TileServer.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def tile_options(self):
        """Gets the tile_options of this TileServer.  # noqa: E501


        :return: The tile_options of this TileServer.  # noqa: E501
        :rtype: object
        """
        return self._tile_options

    @tile_options.setter
    def tile_options(self, tile_options):
        """Sets the tile_options of this TileServer.


        :param tile_options: The tile_options of this TileServer.  # noqa: E501
        :type: object
        """

        self._tile_options = tile_options

    @property
    def type(self):
        """Gets the type of this TileServer.  # noqa: E501


        :return: The type of this TileServer.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this TileServer.


        :param type: The type of this TileServer.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def ui_options(self):
        """Gets the ui_options of this TileServer.  # noqa: E501


        :return: The ui_options of this TileServer.  # noqa: E501
        :rtype: object
        """
        return self._ui_options

    @ui_options.setter
    def ui_options(self, ui_options):
        """Sets the ui_options of this TileServer.


        :param ui_options: The ui_options of this TileServer.  # noqa: E501
        :type: object
        """

        self._ui_options = ui_options

    @property
    def url(self):
        """Gets the url of this TileServer.  # noqa: E501


        :return: The url of this TileServer.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this TileServer.


        :param url: The url of this TileServer.  # noqa: E501
        :type: str
        """

        self._url = url

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TileServer, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TileServer):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, TileServer):
            return True

        return self.to_dict() != other.to_dict()
