# coding: utf-8

"""
    Fingoti API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from fingoti.configuration import Configuration


class DevicePower(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'current': 'int',
        'voltage': 'int',
        'source': 'int'
    }

    attribute_map = {
        'current': 'current',
        'voltage': 'voltage',
        'source': 'source'
    }

    def __init__(self, current=None, voltage=None, source=None, local_vars_configuration=None):  # noqa: E501
        """DevicePower - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._current = None
        self._voltage = None
        self._source = None
        self.discriminator = None

        if current is not None:
            self.current = current
        if voltage is not None:
            self.voltage = voltage
        if source is not None:
            self.source = source

    @property
    def current(self):
        """Gets the current of this DevicePower.  # noqa: E501


        :return: The current of this DevicePower.  # noqa: E501
        :rtype: int
        """
        return self._current

    @current.setter
    def current(self, current):
        """Sets the current of this DevicePower.


        :param current: The current of this DevicePower.  # noqa: E501
        :type current: int
        """

        self._current = current

    @property
    def voltage(self):
        """Gets the voltage of this DevicePower.  # noqa: E501


        :return: The voltage of this DevicePower.  # noqa: E501
        :rtype: int
        """
        return self._voltage

    @voltage.setter
    def voltage(self, voltage):
        """Sets the voltage of this DevicePower.


        :param voltage: The voltage of this DevicePower.  # noqa: E501
        :type voltage: int
        """

        self._voltage = voltage

    @property
    def source(self):
        """Gets the source of this DevicePower.  # noqa: E501


        :return: The source of this DevicePower.  # noqa: E501
        :rtype: int
        """
        return self._source

    @source.setter
    def source(self, source):
        """Sets the source of this DevicePower.


        :param source: The source of this DevicePower.  # noqa: E501
        :type source: int
        """

        self._source = source

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DevicePower):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, DevicePower):
            return True

        return self.to_dict() != other.to_dict()
