# coding: utf-8

"""


    Generated by: https://openapi-generator.tech
"""

import unittest
from unittest.mock import patch

import urllib3

import vrt_lss_packer
from vrt_lss_packer.paths.packer_pack_calculation_async_id import delete  # noqa: E501
from vrt_lss_packer import configuration, schemas, api_client

from .. import ApiTestMixin


class TestPackerPackCalculationAsyncId(ApiTestMixin, unittest.TestCase):
    """
    PackerPackCalculationAsyncId unit test stubs
        Cancel calculation  # noqa: E501
    """
    _configuration = configuration.Configuration()

    def setUp(self):
        used_api_client = api_client.ApiClient(configuration=self._configuration)
        self.api = delete.ApiFordelete(api_client=used_api_client)  # noqa: E501

    def tearDown(self):
        pass

    response_status = 204
    response_body = ''


if __name__ == '__main__':
    unittest.main()
