
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-17T12:10:10-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "9f7d895ab54f9442846d5dd573082d63859cf4c4",
 "version": "0.4.23"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
