from _typeshed import Incomplete
from swimlane.core.fields.base import FieldCursor as FieldCursor, MultiSelectField as MultiSelectField
from swimlane.core.resources.attachment import Attachment as Attachment

class AttachmentCursor(FieldCursor):
    def add(self, filename, stream, content_type: Incomplete | None = ...): ...

class AttachmentsField(MultiSelectField):
    field_type: Incomplete
    cursor_class: Incomplete
    supported_types: Incomplete
    bulk_modify_support: bool
    multiselect: bool
    def __init__(self, *args, **kwargs) -> None: ...
    def get_initial_elements(self): ...
    def get_batch_representation(self): ...
    def cast_to_python(self, value): ...
    def cast_to_swimlane(self, value): ...
