from .base import Field as Field
from _typeshed import Incomplete

UTC: Incomplete

class DatetimeField(Field):
    field_type: str
    datetime_format: str
    supported_types: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def cast_to_python(self, value): ...
    def get_python(self): ...
    @classmethod
    def format_datetime(cls, target_datetime): ...
    def cast_to_swimlane(self, value): ...
    def get_batch_representation(self): ...
    def for_json(self): ...
