
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-17T13:56:23+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "85a7efda2d9c5a0d277d13a0015c77e9e1186f5b",
 "version": "2.2.16"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
