# coding: utf-8

"""
    GeoAPI

    Geospatial API for TAPIS  # noqa: E501

    OpenAPI spec version: 0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import geoapi_client
from geoapi_client.api.notifications_api import NotificationsApi  # noqa: E501
from geoapi_client.rest import ApiException


class TestNotificationsApi(unittest.TestCase):
    """NotificationsApi unit test stubs"""

    def setUp(self):
        self.api = geoapi_client.api.notifications_api.NotificationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete(self):
        """Test case for delete

        """
        pass

    def test_delete_0(self):
        """Test case for delete_0

        """
        pass

    def test_get(self):
        """Test case for get

        """
        pass

    def test_get_0(self):
        """Test case for get_0

        """
        pass

    def test_get_1(self):
        """Test case for get_1

        """
        pass


if __name__ == '__main__':
    unittest.main()
