# coding: utf-8

"""
    GeoAPI

    Geospatial API for TAPIS  # noqa: E501

    OpenAPI spec version: 0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import geoapi_client
from geoapi_client.api.streetview_api import StreetviewApi  # noqa: E501
from geoapi_client.rest import ApiException


class TestStreetviewApi(unittest.TestCase):
    """StreetviewApi unit test stubs"""

    def setUp(self):
        self.api = geoapi_client.api.streetview_api.StreetviewApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_streetview_sequence(self):
        """Test case for add_streetview_sequence

        """
        pass

    def test_create_streetview_organizations(self):
        """Test case for create_streetview_organizations

        """
        pass

    def test_create_streetview_service_resource(self):
        """Test case for create_streetview_service_resource

        """
        pass

    def test_delete_streetview_instance(self):
        """Test case for delete_streetview_instance

        """
        pass

    def test_delete_streetview_organization(self):
        """Test case for delete_streetview_organization

        """
        pass

    def test_delete_streetview_sequence(self):
        """Test case for delete_streetview_sequence

        """
        pass

    def test_delete_streetview_service_resource(self):
        """Test case for delete_streetview_service_resource

        """
        pass

    def test_get_streetview_organizations(self):
        """Test case for get_streetview_organizations

        """
        pass

    def test_get_streetview_sequence(self):
        """Test case for get_streetview_sequence

        """
        pass

    def test_get_streetview_service_resource(self):
        """Test case for get_streetview_service_resource

        """
        pass

    def test_get_streetview_service_resources(self):
        """Test case for get_streetview_service_resources

        """
        pass

    def test_publish_files_to_streetview(self):
        """Test case for publish_files_to_streetview

        """
        pass

    def test_update_streetview_organization(self):
        """Test case for update_streetview_organization

        """
        pass

    def test_update_streetview_sequence(self):
        """Test case for update_streetview_sequence

        """
        pass

    def test_update_streetview_service_resource(self):
        """Test case for update_streetview_service_resource

        """
        pass


if __name__ == '__main__':
    unittest.main()
