from .base import CursorField as CursorField
from _typeshed import Incomplete
from swimlane.core.fields.base import FieldCursor as FieldCursor
from swimlane.exceptions import ValidationError as ValidationError

SID: Incomplete

class _ListFieldCursor(FieldCursor):
    def __getattr__(self, item): ...

class TextListFieldCursor(_ListFieldCursor): ...
class NumericListFieldCursor(_ListFieldCursor): ...

class ListField(CursorField):
    field_type: Incomplete
    cursor_class: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def set_swimlane(self, value): ...
    def set_python(self, value): ...
    def cast_to_swimlane(self, value): ...
    def cast_to_bulk_modify(self, value): ...
