
# This file was generated by 'versioneer.py' (0.16+dev) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "d0fa4b60be562d9a77f660452f7713de0b7375e4",
 "version": "3.4.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
