from _typeshed import Incomplete

class Cursor:
    def __init__(self) -> None: ...
    def __len__(self): ...
    def __iter__(self): ...
    def __getitem__(self, item): ...

class PaginatedCursor(Cursor):
    default_limit: int
    default_page_size: int
    page_size: Incomplete
    def __init__(self, limit=..., page_size=...) -> None: ...
