VERSION_YEAR = 2023
VERSION_MONTH = int('01')
VERSION_DAY = int('15')
VERSION_HOUR = int('09')
VERSION_MINUTE = int('27')
MAJOR_VERSION = 1
MINOR_VERSION = 9
PATCH_VERSION = 202301150927
version_date = '2023/01/15 09:27'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
