
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-18T08:42:06+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "0f4e822b7f005e3d0ed61e0376d0d6ba921ec3d9",
 "version": "0.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
