from _typeshed import Incomplete
from swimlane.core.resources.base import APIResource as APIResource

class Attachment(APIResource):
    file_id: Incomplete
    filename: Incomplete
    upload_date: Incomplete
    def __init__(self, swimlane, raw) -> None: ...
    def __hash__(self): ...
    def download(self, chunk_size: int = ...): ...
    def for_json(self): ...
