# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: point_stamped.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import header_pb2 as header__pb2
import point_pb2 as point__pb2
import labels_with_instance_with_category_pb2 as labels__with__instance__with__category__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13point_stamped.proto\x12\x06seerep\x1a\x0cheader.proto\x1a\x0bpoint.proto\x1a(labels_with_instance_with_category.proto\"\x8c\x01\n\x0cPointStamped\x12\x1e\n\x06header\x18\x01 \x01(\x0b\x32\x0e.seerep.Header\x12\x1c\n\x05point\x18\x02 \x01(\x0b\x32\r.seerep.Point\x12>\n\x0elabels_general\x18\x03 \x03(\x0b\x32&.seerep.LabelsWithInstanceWithCategoryb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'point_stamped_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _POINTSTAMPED._serialized_start=101
  _POINTSTAMPED._serialized_end=241
# @@protoc_insertion_point(module_scope)
