from typing import Union

EDUCOURSE_OID: str
EDUPERSON_OID: str
EDUMEMBER1_OID: str
LDAPGVAT_OID: str
UCL_DIR_PILOT: str
X500ATTR_OID: str
LDAPGVAT_UCL_DIR_PILOT: str
LDAPGVAT_X500ATTR_OID: str
NETSCAPE_LDAP: str
NOREDUPERSON_OID: str
PKCS_9: str
SCHAC: str
SIS: str
UMICH: str
OPENOSI_OID: str
SWISSEDUPERSON_OID: str
EIDAS_NATURALPERSON: str
EIDAS_LEGALPERSON: str
SAML_SUBJECT_ID: str
UMBRELLA_EAAUser_ID: str
PKIX_OID: str
INERA_OID: str
DIGG_OID: str
MAP: dict[str, Union[str, dict[str, str]]]
