# coding: utf-8

"""
    GeoAPI

    Geospatial API for TAPIS  # noqa: E501

    OpenAPI spec version: 0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from geoapi_client.configuration import Configuration


class Asset(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'asset_type': 'str',
        'display_path': 'str',
        'id': 'int',
        'original_name': 'str',
        'original_path': 'str',
        'path': 'str',
        'uuid': 'str'
    }

    attribute_map = {
        'asset_type': 'asset_type',
        'display_path': 'display_path',
        'id': 'id',
        'original_name': 'original_name',
        'original_path': 'original_path',
        'path': 'path',
        'uuid': 'uuid'
    }

    def __init__(self, asset_type=None, display_path=None, id=None, original_name=None, original_path=None, path=None, uuid=None, _configuration=None):  # noqa: E501
        """Asset - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._asset_type = None
        self._display_path = None
        self._id = None
        self._original_name = None
        self._original_path = None
        self._path = None
        self._uuid = None
        self.discriminator = None

        if asset_type is not None:
            self.asset_type = asset_type
        if display_path is not None:
            self.display_path = display_path
        if id is not None:
            self.id = id
        if original_name is not None:
            self.original_name = original_name
        if original_path is not None:
            self.original_path = original_path
        if path is not None:
            self.path = path
        if uuid is not None:
            self.uuid = uuid

    @property
    def asset_type(self):
        """Gets the asset_type of this Asset.  # noqa: E501


        :return: The asset_type of this Asset.  # noqa: E501
        :rtype: str
        """
        return self._asset_type

    @asset_type.setter
    def asset_type(self, asset_type):
        """Sets the asset_type of this Asset.


        :param asset_type: The asset_type of this Asset.  # noqa: E501
        :type: str
        """

        self._asset_type = asset_type

    @property
    def display_path(self):
        """Gets the display_path of this Asset.  # noqa: E501


        :return: The display_path of this Asset.  # noqa: E501
        :rtype: str
        """
        return self._display_path

    @display_path.setter
    def display_path(self, display_path):
        """Sets the display_path of this Asset.


        :param display_path: The display_path of this Asset.  # noqa: E501
        :type: str
        """

        self._display_path = display_path

    @property
    def id(self):
        """Gets the id of this Asset.  # noqa: E501


        :return: The id of this Asset.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Asset.


        :param id: The id of this Asset.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def original_name(self):
        """Gets the original_name of this Asset.  # noqa: E501


        :return: The original_name of this Asset.  # noqa: E501
        :rtype: str
        """
        return self._original_name

    @original_name.setter
    def original_name(self, original_name):
        """Sets the original_name of this Asset.


        :param original_name: The original_name of this Asset.  # noqa: E501
        :type: str
        """

        self._original_name = original_name

    @property
    def original_path(self):
        """Gets the original_path of this Asset.  # noqa: E501


        :return: The original_path of this Asset.  # noqa: E501
        :rtype: str
        """
        return self._original_path

    @original_path.setter
    def original_path(self, original_path):
        """Sets the original_path of this Asset.


        :param original_path: The original_path of this Asset.  # noqa: E501
        :type: str
        """

        self._original_path = original_path

    @property
    def path(self):
        """Gets the path of this Asset.  # noqa: E501


        :return: The path of this Asset.  # noqa: E501
        :rtype: str
        """
        return self._path

    @path.setter
    def path(self, path):
        """Sets the path of this Asset.


        :param path: The path of this Asset.  # noqa: E501
        :type: str
        """

        self._path = path

    @property
    def uuid(self):
        """Gets the uuid of this Asset.  # noqa: E501


        :return: The uuid of this Asset.  # noqa: E501
        :rtype: str
        """
        return self._uuid

    @uuid.setter
    def uuid(self, uuid):
        """Sets the uuid of this Asset.


        :param uuid: The uuid of this Asset.  # noqa: E501
        :type: str
        """

        self._uuid = uuid

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Asset, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Asset):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Asset):
            return True

        return self.to_dict() != other.to_dict()
