from typing import Any

NAMESPACE: str
ENCODING_BASE64: str
DIGEST_MD5: str
DIGEST_SHA1: str
DIGEST_SHA224: str
DIGEST_SHA256: str
DIGEST_SHA384: str
DIGEST_SHA512: str
DIGEST_RIPEMD160: str
digest_default: str
SIG_DSA_SHA1: str
SIG_DSA_SHA256: str
SIG_ECDSA_SHA1: str
SIG_ECDSA_SHA224: str
SIG_ECDSA_SHA256: str
SIG_ECDSA_SHA384: str
SIG_ECDSA_SHA512: str
SIG_RSA_MD5: str
SIG_RSA_SHA1: str
SIG_RSA_SHA224: str
SIG_RSA_SHA256: str
SIG_RSA_SHA384: str
SIG_RSA_SHA512: str
SIG_RSA_RIPEMD160: str
sig_default: str
SIG_ALLOWED_ALG: Any
SIG_AVAIL_ALG: Any
MAC_SHA1: str
TRANSFORM_XSLT: str
TRANSFORM_XPATH: str
TRANSFORM_ENVELOPED: str
TRANSFORM_C14N: str
TRANSFORM_C14N_WITH_COMMENTS: str

def __getattr__(name: str) -> Any: ...  # incomplete
