# coding: utf-8

"""
    VRt.Studio [ST]

    Veeroute Studio API.  # Description  Server part of the studio.  ## Entity relationship diagram  ![erd](../uml/studio.svg)  # noqa: E501

    The version of the OpenAPI document: 5.12.1831
    Contact: servicedesk@veeroute.com
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from vrt_lss_studio import schemas  # noqa: F401


class BasicState(
    schemas.EnumBase,
    schemas.StrSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Essence state.

    """


    class MetaOapg:
        enum_value_to_name = {
            "PLANNED": "PLANNED",
            "ASSIGNED": "ASSIGNED",
            "UNPLANNED": "UNPLANNED",
            "ERROR": "ERROR",
        }
    
    @schemas.classproperty
    def PLANNED(cls):
        return cls("PLANNED")
    
    @schemas.classproperty
    def ASSIGNED(cls):
        return cls("ASSIGNED")
    
    @schemas.classproperty
    def UNPLANNED(cls):
        return cls("UNPLANNED")
    
    @schemas.classproperty
    def ERROR(cls):
        return cls("ERROR")
