# coding: utf-8

"""
    VRt.Studio [ST]

    Veeroute Studio API.  # Description  Server part of the studio.  ## Entity relationship diagram  ![erd](../uml/studio.svg)  # noqa: E501

    The version of the OpenAPI document: 5.12.1831
    Contact: servicedesk@veeroute.com
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from vrt_lss_studio import schemas  # noqa: F401


class TableFilterType(
    schemas.EnumBase,
    schemas.StrSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Filter type:
  * `DATETIME_RANGE` - intersection of the time interval
  * `INT_RANGE` - getting a number inside an integer segment
  * `FLOAT_RANGE` - hitting the number inside the float segment
  * `BOOL_LIST` - exact match of boolean values
  * `ENUM_LIST` - exact match of string values from enum
  * `STRING_LIST` - partial match of a subset of string values
  * `STRING_SEARCH` - partial match of a string

    """


    class MetaOapg:
        enum_value_to_name = {
            "DATETIME_RANGE": "DATETIME_RANGE",
            "INT_RANGE": "INT_RANGE",
            "FLOAT_RANGE": "FLOAT_RANGE",
            "BOOL_LIST": "BOOL_LIST",
            "ENUM_LIST": "ENUM_LIST",
            "STRING_LIST": "STRING_LIST",
            "STRING_SEARCH": "STRING_SEARCH",
        }
    
    @schemas.classproperty
    def DATETIME_RANGE(cls):
        return cls("DATETIME_RANGE")
    
    @schemas.classproperty
    def INT_RANGE(cls):
        return cls("INT_RANGE")
    
    @schemas.classproperty
    def FLOAT_RANGE(cls):
        return cls("FLOAT_RANGE")
    
    @schemas.classproperty
    def BOOL_LIST(cls):
        return cls("BOOL_LIST")
    
    @schemas.classproperty
    def ENUM_LIST(cls):
        return cls("ENUM_LIST")
    
    @schemas.classproperty
    def STRING_LIST(cls):
        return cls("STRING_LIST")
    
    @schemas.classproperty
    def STRING_SEARCH(cls):
        return cls("STRING_SEARCH")
