# coding: utf-8

"""
    VRt.Studio [ST]

    Veeroute Studio API.  # Description  Server part of the studio.  ## Entity relationship diagram  ![erd](../uml/studio.svg)  # noqa: E501

    The version of the OpenAPI document: 5.12.1831
    Contact: servicedesk@veeroute.com
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from vrt_lss_studio import schemas  # noqa: F401


class TableLocationColumnType(
    schemas.EnumBase,
    schemas.StrSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Locations table column name.

    """


    class MetaOapg:
        enum_value_to_name = {
            "ESSENCE_KEY": "ESSENCE_KEY",
            "ENABLED": "ENABLED",
            "PRISTINE": "PRISTINE",
            "WORKING_TIME": "WORKING_TIME",
        }
    
    @schemas.classproperty
    def ESSENCE_KEY(cls):
        return cls("ESSENCE_KEY")
    
    @schemas.classproperty
    def ENABLED(cls):
        return cls("ENABLED")
    
    @schemas.classproperty
    def PRISTINE(cls):
        return cls("PRISTINE")
    
    @schemas.classproperty
    def WORKING_TIME(cls):
        return cls("WORKING_TIME")
