# coding: utf-8

"""
    VRt.Studio [ST]

    Veeroute Studio API.  # Description  Server part of the studio.  ## Entity relationship diagram  ![erd](../uml/studio.svg)  # noqa: E501

    The version of the OpenAPI document: 5.12.1831
    Contact: servicedesk@veeroute.com
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from vrt_lss_studio import schemas  # noqa: F401


class TransportType(
    schemas.EnumBase,
    schemas.StrSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Transport types:
  * `CAR` - car
  * `TRUCK_1500` - truck with permissible weight 1500 kg
  * `TRUCK_3000` - truck with permissible weight 3000 kg
  * `TRUCK_5000` - truck with permissible weight 5000 kg
  * `TRUCK_10000` - truck with permissible weight 10000 kg
  * `TRUCK_20000` - truck with permissible weight 20000 kg
  * `TUK_TUK` - tuk-tuk
  * `BICYCLE` - bicycle
  * `PEDESTRIAN` - pedestrian      
  * `PUBLIC_TRANSPORT` - public transport

    """


    class MetaOapg:
        enum_value_to_name = {
            "CAR": "CAR",
            "TRUCK_1500": "TRUCK_1500",
            "TRUCK_3000": "TRUCK_3000",
            "TRUCK_5000": "TRUCK_5000",
            "TRUCK_10000": "TRUCK_10000",
            "TRUCK_20000": "TRUCK_20000",
            "TUK_TUK": "TUK_TUK",
            "BICYCLE": "BICYCLE",
            "PEDESTRIAN": "PEDESTRIAN",
            "PUBLIC_TRANSPORT": "PUBLIC_TRANSPORT",
        }
    
    @schemas.classproperty
    def CAR(cls):
        return cls("CAR")
    
    @schemas.classproperty
    def TRUCK_1500(cls):
        return cls("TRUCK_1500")
    
    @schemas.classproperty
    def TRUCK_3000(cls):
        return cls("TRUCK_3000")
    
    @schemas.classproperty
    def TRUCK_5000(cls):
        return cls("TRUCK_5000")
    
    @schemas.classproperty
    def TRUCK_10000(cls):
        return cls("TRUCK_10000")
    
    @schemas.classproperty
    def TRUCK_20000(cls):
        return cls("TRUCK_20000")
    
    @schemas.classproperty
    def TUK_TUK(cls):
        return cls("TUK_TUK")
    
    @schemas.classproperty
    def BICYCLE(cls):
        return cls("BICYCLE")
    
    @schemas.classproperty
    def PEDESTRIAN(cls):
        return cls("PEDESTRIAN")
    
    @schemas.classproperty
    def PUBLIC_TRANSPORT(cls):
        return cls("PUBLIC_TRANSPORT")
