# coding: utf-8

"""
    VRt.Studio [ST]

    Veeroute Studio API.  # Description  Server part of the studio.  ## Entity relationship diagram  ![erd](../uml/studio.svg)  # noqa: E501

    The version of the OpenAPI document: 5.12.1831
    Contact: servicedesk@veeroute.com
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from vrt_lss_studio import schemas  # noqa: F401


class TripStartTimeStrategy(
    schemas.EnumBase,
    schemas.StrSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    The strategy of the choosing optimal trip start time:
  * `EARLIEST_FINISH`
  * `LOWEST_COST`

    """


    class MetaOapg:
        enum_value_to_name = {
            "EARLIEST_FINISH": "EARLIEST_FINISH",
            "LOWEST_COST": "LOWEST_COST",
        }
    
    @schemas.classproperty
    def EARLIEST_FINISH(cls):
        return cls("EARLIEST_FINISH")
    
    @schemas.classproperty
    def LOWEST_COST(cls):
        return cls("LOWEST_COST")
