from ..helpers import article as article, fsd as fsd, untangle as untangle, z as z
from ._helpers import Enr2Scheme as Enr2Scheme
from _typeshed import Incomplete

source: Incomplete

def stenger_7a(dim): ...
def stenger_7b(dim): ...
def stenger_9a(dim): ...
def stenger_9b(dim): ...
def stenger_11a(dim): ...
def stenger_11b(dim): ...
