from ._helpers import C1Scheme as C1Scheme
from _typeshed import Incomplete

def chebyshev_gauss_1(n, mode: str = ...): ...
def chebyshev_gauss_2(n, mode: str = ..., decimal_places: Incomplete | None = ...): ...
