
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-19T14:39:03+1100",
 "dirty": false,
 "error": null,
 "full-revisionid": "3b446a13556fd9e764a9394ac4f346323e3dde2a",
 "version": "0.16.3.post7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
