
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-18T15:05:48-0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "0f41e6cd526051fc729f30e492fe2c56c3c588a0",
 "version": "0.1.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
