from mathPkg.mathPkg import addnum
from mathPkg.mathPkg import subnum
from mathPkg.mathPkg import mulnum
from mathPkg.mathPkg import divnum
from mathPkg.mathPkg import pownum
from mathPkg.mathPkg import prime_num
from mathPkg.mathPkg import is_palindrome
from mathPkg.mathPkg import is_armstrong
from mathPkg.mathPkg import even_odd_num