VERSION_YEAR = 2023
VERSION_MONTH = int('01')
VERSION_DAY = int('18')
VERSION_HOUR = int('16')
VERSION_MINUTE = int('13')
MAJOR_VERSION = 1
MINOR_VERSION = 9
PATCH_VERSION = 202301181613
version_date = '2023/01/18 16:13'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
