# coding: utf-8

"""
    VRt.Agro [AG]

    Veeroute Agro API.  # Description  The service is designed to calculate the work plan of production facilities.  ## Objects overview  ![objects](../images/agro_objects.svg)  ## Entity relationship diagram  ![erd](../uml/agro.svg)  # noqa: E501

    The version of the OpenAPI document: 5.12.1831
    Contact: servicedesk@veeroute.com
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from vrt_lss_agro import schemas  # noqa: F401


class OperationType(
    schemas.EnumBase,
    schemas.StrSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Operation type.

    """


    class MetaOapg:
        enum_value_to_name = {
            "HARVEST": "HARVEST",
            "STORAGE": "STORAGE",
            "DRYING": "DRYING",
            "MOVEMENT": "MOVEMENT",
            "TRANSFER": "TRANSFER",
            "CONSUMPTION": "CONSUMPTION",
            "SELLING": "SELLING",
            "BUYING": "BUYING",
        }
    
    @schemas.classproperty
    def HARVEST(cls):
        return cls("HARVEST")
    
    @schemas.classproperty
    def STORAGE(cls):
        return cls("STORAGE")
    
    @schemas.classproperty
    def DRYING(cls):
        return cls("DRYING")
    
    @schemas.classproperty
    def MOVEMENT(cls):
        return cls("MOVEMENT")
    
    @schemas.classproperty
    def TRANSFER(cls):
        return cls("TRANSFER")
    
    @schemas.classproperty
    def CONSUMPTION(cls):
        return cls("CONSUMPTION")
    
    @schemas.classproperty
    def SELLING(cls):
        return cls("SELLING")
    
    @schemas.classproperty
    def BUYING(cls):
        return cls("BUYING")
