
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-15T18:51:52+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "1a39632b8518ab2cce4eecd2fca437b7506065b3",
 "version": "0.13.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
