"""
    Synctera API

    <h2>Let's build something great.</h2><p>Welcome to the official reference documentation for Synctera APIs. Our APIs are the best way to automate your company's banking needs and are designed to be easy to understand and implement.</p><p>We're continuously growing this library and what you see here is just the start, but if you need something specific or have a question, <a class='text-blue-600' href='https://synctera.com/contact' target='_blank' rel='noreferrer'>contact us</a>.</p>   # noqa: E501

    The version of the OpenAPI document: 0.32.0
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from synctera_client.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
    OpenApiModel
)
from synctera_client.exceptions import ApiAttributeError


def lazy_import():
    from synctera_client.model.card_metadata import CardMetadata
    from synctera_client.model.emboss_name import EmbossName
    globals()['CardMetadata'] = CardMetadata
    globals()['EmbossName'] = EmbossName


class BaseCardAllOf(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
        ('reissue_reason',): {
            'EXPIRATION': "EXPIRATION",
            'LOST': "LOST",
            'STOLEN': "STOLEN",
            'DAMAGED': "DAMAGED",
            'NAME_CHANGE': "NAME_CHANGE",
            'VIRTUAL_TO_PHYSICAL': "VIRTUAL_TO_PHYSICAL",
            'PRODUCT_CHANGE': "PRODUCT_CHANGE",
            'APPEARANCE': "APPEARANCE",
        },
        ('type',): {
            'DEBIT': "DEBIT",
        },
    }

    validations = {
    }

    @cached_property
    def additional_properties_type():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded
        """
        lazy_import()
        return (bool, date, datetime, dict, float, int, list, str, none_type,)  # noqa: E501

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        lazy_import()
        return {
            'account_id': (str,),  # noqa: E501
            'card_product_id': (str,),  # noqa: E501
            'creation_time': (datetime,),  # noqa: E501
            'customer_id': (str,),  # noqa: E501
            'emboss_name': (EmbossName,),  # noqa: E501
            'expiration_month': (str,),  # noqa: E501
            'expiration_time': (datetime,),  # noqa: E501
            'expiration_year': (str,),  # noqa: E501
            'id': (str,),  # noqa: E501
            'is_pin_set': (bool,),  # noqa: E501
            'last_four': (str,),  # noqa: E501
            'last_modified_time': (datetime,),  # noqa: E501
            'metadata': (CardMetadata,),  # noqa: E501
            'reissue_reason': (str,),  # noqa: E501
            'reissued_from_id': (str,),  # noqa: E501
            'reissued_to_id': (str,),  # noqa: E501
            'type': (str,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'account_id': 'account_id',  # noqa: E501
        'card_product_id': 'card_product_id',  # noqa: E501
        'creation_time': 'creation_time',  # noqa: E501
        'customer_id': 'customer_id',  # noqa: E501
        'emboss_name': 'emboss_name',  # noqa: E501
        'expiration_month': 'expiration_month',  # noqa: E501
        'expiration_time': 'expiration_time',  # noqa: E501
        'expiration_year': 'expiration_year',  # noqa: E501
        'id': 'id',  # noqa: E501
        'is_pin_set': 'is_pin_set',  # noqa: E501
        'last_four': 'last_four',  # noqa: E501
        'last_modified_time': 'last_modified_time',  # noqa: E501
        'metadata': 'metadata',  # noqa: E501
        'reissue_reason': 'reissue_reason',  # noqa: E501
        'reissued_from_id': 'reissued_from_id',  # noqa: E501
        'reissued_to_id': 'reissued_to_id',  # noqa: E501
        'type': 'type',  # noqa: E501
    }

    read_only_vars = {
        'creation_time',  # noqa: E501
        'expiration_month',  # noqa: E501
        'expiration_time',  # noqa: E501
        'expiration_year',  # noqa: E501
        'id',  # noqa: E501
        'is_pin_set',  # noqa: E501
        'last_four',  # noqa: E501
        'last_modified_time',  # noqa: E501
        'reissued_to_id',  # noqa: E501
    }

    _composed_schemas = {}

    @classmethod
    @convert_js_args_to_python_args
    def _from_openapi_data(cls, *args, **kwargs):  # noqa: E501
        """BaseCardAllOf - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            account_id (str): The ID of the account to which the card will be linked. [optional]  # noqa: E501
            card_product_id (str): The card product to which the card is attached. [optional]  # noqa: E501
            creation_time (datetime): The timestamp representing when the card issuance request was made. [optional]  # noqa: E501
            customer_id (str): The ID of the customer to whom the card will be issued. [optional]  # noqa: E501
            emboss_name (EmbossName): [optional]  # noqa: E501
            expiration_month (str): [optional]  # noqa: E501
            expiration_time (datetime): The timestamp representing when the card would expire at. [optional]  # noqa: E501
            expiration_year (str): [optional]  # noqa: E501
            id (str): Card ID. [optional]  # noqa: E501
            is_pin_set (bool): indicates whether a pin has been set on the card. [optional] if omitted the server will use the default value of False  # noqa: E501
            last_four (str): The last 4 digits of the card PAN. [optional]  # noqa: E501
            last_modified_time (datetime): The timestamp representing when the card was last modified at. [optional]  # noqa: E501
            metadata (CardMetadata): [optional]  # noqa: E501
            reissue_reason (str): This is the reason the card needs to be reissued, if any. The reason determines several behaviours:   - whether or not the new card will use the same PAN as the original card   - the old card will be terminated and if so, when it will be terminated  Reason                 | Same PAN | Terminate Old Card ---------------------- | -------- | ------------------ EXPIRATION             | yes      | on activation LOST                   | no       | immediately STOLEN                 | no       | immediately DAMAGED                | yes      | on activation VIRTUAL_TO_PHYSICAL(*) | yes      | on activation PRODUCT_CHANGE         | yes      | on activation NAME_CHANGE(**)        | yes      | on activation APPEARANCE             | yes      | on activation  (*) VIRTUAL_TO_PHYSICAL is deprecated. Please use PRODUCT_CHANGE whenever reissuing from one card product to another, including from a virtual product to a physical product.  (**) NAME_CHANGE is deprecated. Please use APPEARANCE whenever reissuing in order to change the appearance of a card, such as the printed name or custom image.  For all reasons, the new card will use the same PIN as the original card and digital wallet tokens will reassigned to the new card . [optional]  # noqa: E501
            reissued_from_id (str): When reissuing a card, specify the card to be replaced here. When getting a card's details, if this card was issued as a reissuance of another card, this ID refers to the card was replaced. If this field is set, then reissue_reason must also be set. . [optional]  # noqa: E501
            reissued_to_id (str): If this card was reissued, this ID refers to the card that replaced it.. [optional]  # noqa: E501
            type (str): Indicates the type of card to be issued. [optional] if omitted the server will use the default value of "DEBIT"  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', True)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        self = super(OpenApiModel, cls).__new__(cls)

        if args:
            for arg in args:
                if isinstance(arg, dict):
                    kwargs.update(arg)
                else:
                    raise ApiTypeError(
                        "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                            args,
                            self.__class__.__name__,
                        ),
                        path_to_item=_path_to_item,
                        valid_classes=(self.__class__,),
                    )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
        return self

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, *args, **kwargs):  # noqa: E501
        """BaseCardAllOf - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            account_id (str): The ID of the account to which the card will be linked. [optional]  # noqa: E501
            card_product_id (str): The card product to which the card is attached. [optional]  # noqa: E501
            creation_time (datetime): The timestamp representing when the card issuance request was made. [optional]  # noqa: E501
            customer_id (str): The ID of the customer to whom the card will be issued. [optional]  # noqa: E501
            emboss_name (EmbossName): [optional]  # noqa: E501
            expiration_month (str): [optional]  # noqa: E501
            expiration_time (datetime): The timestamp representing when the card would expire at. [optional]  # noqa: E501
            expiration_year (str): [optional]  # noqa: E501
            id (str): Card ID. [optional]  # noqa: E501
            is_pin_set (bool): indicates whether a pin has been set on the card. [optional] if omitted the server will use the default value of False  # noqa: E501
            last_four (str): The last 4 digits of the card PAN. [optional]  # noqa: E501
            last_modified_time (datetime): The timestamp representing when the card was last modified at. [optional]  # noqa: E501
            metadata (CardMetadata): [optional]  # noqa: E501
            reissue_reason (str): This is the reason the card needs to be reissued, if any. The reason determines several behaviours:   - whether or not the new card will use the same PAN as the original card   - the old card will be terminated and if so, when it will be terminated  Reason                 | Same PAN | Terminate Old Card ---------------------- | -------- | ------------------ EXPIRATION             | yes      | on activation LOST                   | no       | immediately STOLEN                 | no       | immediately DAMAGED                | yes      | on activation VIRTUAL_TO_PHYSICAL(*) | yes      | on activation PRODUCT_CHANGE         | yes      | on activation NAME_CHANGE(**)        | yes      | on activation APPEARANCE             | yes      | on activation  (*) VIRTUAL_TO_PHYSICAL is deprecated. Please use PRODUCT_CHANGE whenever reissuing from one card product to another, including from a virtual product to a physical product.  (**) NAME_CHANGE is deprecated. Please use APPEARANCE whenever reissuing in order to change the appearance of a card, such as the printed name or custom image.  For all reasons, the new card will use the same PIN as the original card and digital wallet tokens will reassigned to the new card . [optional]  # noqa: E501
            reissued_from_id (str): When reissuing a card, specify the card to be replaced here. When getting a card's details, if this card was issued as a reissuance of another card, this ID refers to the card was replaced. If this field is set, then reissue_reason must also be set. . [optional]  # noqa: E501
            reissued_to_id (str): If this card was reissued, this ID refers to the card that replaced it.. [optional]  # noqa: E501
            type (str): Indicates the type of card to be issued. [optional] if omitted the server will use the default value of "DEBIT"  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            for arg in args:
                if isinstance(arg, dict):
                    kwargs.update(arg)
                else:
                    raise ApiTypeError(
                        "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                            args,
                            self.__class__.__name__,
                        ),
                        path_to_item=_path_to_item,
                        valid_classes=(self.__class__,),
                    )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
            if var_name in self.read_only_vars:
                raise ApiAttributeError(f"`{var_name}` is a read-only attribute. Use `from_openapi_data` to instantiate "
                                     f"class with read only attributes.")
