
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-18T19:32:08+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "bbdd8a26de56d7080b897fc290afc0c0418da768",
 "version": "0.2.61.post0.dev4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
