# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stress.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StressAnalysis(object):
    def setupUi(self, StressAnalysis):
        StressAnalysis.setObjectName("StressAnalysis")
        StressAnalysis.resize(1000, 500)
        StressAnalysis.setMinimumSize(QtCore.QSize(1000, 500))
        self.verticalLayout = QtWidgets.QVBoxLayout(StressAnalysis)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter = QtWidgets.QSplitter(StressAnalysis)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.measurements = QtWidgets.QTreeWidget(self.splitter)
        self.measurements.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.measurements.setRootIsDecorated(True)
        self.measurements.setColumnCount(2)
        self.measurements.setObjectName("measurements")
        self.measurements.headerItem().setText(0, "1")
        self.measurements.headerItem().setText(1, "2")
        self.measurements.header().setVisible(False)
        self.verticalLayout.addWidget(self.splitter)

        self.retranslateUi(StressAnalysis)
        QtCore.QMetaObject.connectSlotsByName(StressAnalysis)

    def retranslateUi(self, StressAnalysis):
        _translate = QtCore.QCoreApplication.translate
        StressAnalysis.setWindowTitle(_translate("StressAnalysis", "Stress Analysis"))
