from typing import Any

NAMESPACE: str
STATUS_SUCCESS: str
STATUS_REQUESTER: str
STATUS_RESPONDER: str
STATUS_VERSION_MISMATCH: str
STATUS_AUTHN_FAILED: str
STATUS_INVALID_ATTR_NAME_OR_VALUE: str
STATUS_INVALID_NAMEID_POLICY: str
STATUS_NO_AUTHN_CONTEXT: str
STATUS_NO_AVAILABLE_IDP: str
STATUS_NO_PASSIVE: str
STATUS_NO_SUPPORTED_IDP: str
STATUS_PARTIAL_LOGOUT: str
STATUS_PROXY_COUNT_EXCEEDED: str
STATUS_REQUEST_DENIED: str
STATUS_REQUEST_UNSUPPORTED: str
STATUS_REQUEST_VERSION_DEPRECATED: str
STATUS_REQUEST_VERSION_TOO_HIGH: str
STATUS_REQUEST_VERSION_TOO_LOW: str
STATUS_RESOURCE_NOT_RECOGNIZED: str
STATUS_TOO_MANY_RESPONSES: str
STATUS_UNKNOWN_ATTR_PROFILE: str
STATUS_UNKNOWN_PRINCIPAL: str
STATUS_UNSUPPORTED_BINDING: str

def __getattr__(name: str) -> Any: ...  # incomplete
