
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-17T14:31:47+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "3cc23d600a72615f6e223288592d9e14adcc2606",
 "version": "2.2.17"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
