# no genitive and no other noun definition than bunamo
# (partial list)
BUNAMO_ONLY_GENITIVELESS = [
    'dipín', 'ac', 'rac', 'carrac', 'gúsnaic', 'traic', 'téic', 'ruc',
    'búitíc', 'dearbhmhéid', 'fíd', 'blag', 'stoing', 'réabh', 'cúlstagh',
    'taicil', 'móideim', 'iomám', 'treoirphlean', 'muaisin', 'abhatár',
    'neasphas', 'ailias', 'seat', 'búit', 'boghspriot'
]

POSSIBLE_LOANWORDS_GENITIVELESS = [
    'ailím',
    'aintín',
    'apacailipsis',
    'basal',
    'beirilliam',
    'biogóid',
    'blitz',
    'bob',
    'bunc  # in BuNaMo and Wiktionary',
    'bus',
    #cadhc',
    'call',
    'carst',
    'ceaig',
    'ceilvin',
    'ceirbheacs',
    'cic',
    'clinic',
    'club',
    'Comaoineach',
    'Críost',
    'cróch',
    'dabht',
    'daid',
    'dosaen',
    'fabht',
    'fastaím',
    'fean',
    'franc',
    'fuist',
    'geab',
    'geiréiniam',
    'gigiheirts',
    'gild',
    'giúistís',
    'hap',
    'héileapad',
    'hiopstar',
    'jab',
    'jíp',
    'jóc',
    'Laos',
    'leaid',
    'Madagascar',
    'maidhc',
    'Máirt',
    'matrarc',
    'meigiheirts',
    'meireang',
    'Meisias',
    'miorr',
    'monarc',
    'mosc',
    'nanashoicind',
    'Oiríon',
    'Óman',
    'pas',
    'patrarc',
    'péas',
    'Peintiteoch',
    'Pilib',
    'pioc',
    'píoláf',
    'pionsail',
    'píoráid',
    'plean',
    'pontaif',
    'pram',
    'punc',
    'raidhfil',
    'raifil',
    'rascail',
    'rúbarb',
    'rum',
    'sáirsint',
    'seaimpéin',
    'seic',
    'seilf',
    'seirbhísiú',
    'seit',
    'síc',
    'siút',
    'slám',
    'soicind',
    'speár',
    'stop',
    'stróc',
    'stuif',
    'tanc',
    'tic',
    'tinsil',
    'tobac',
    'traidhfil',
    'tram',
    'uncail',
    'vác',
    'veain',
    'Véineas',
    'zip',

    # compound with loanword
    'rotharchic',
    'saorchic',
    'mionbhus',
]
