# coding: utf-8

"""
    VRt.Routing [RO]

    # Description  **VRt.Routing** is designed to find a route between locations and build time-distance matrices.  ## Features  * Getting the distance and time between two locations, including traffic jams * Finding a route between specified locations * Creating a time-distance matrix  ## Entity relationship diagram  ![erd](../uml/routing.svg)  # noqa: E501

    The version of the OpenAPI document: 5.12.1831
    Contact: servicedesk@veeroute.com
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from vrt_lss_routing import schemas  # noqa: F401


class ServiceName(
    schemas.EnumBase,
    schemas.StrSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Service name.
    """


    class MetaOapg:
        enum_value_to_name = {
            "UNIVERSAL": "UNIVERSAL",
            "ROUTING": "ROUTING",
            "ACCOUNT": "ACCOUNT",
            "ADMIN": "ADMIN",
            "STUDIO": "STUDIO",
            "PACKER": "PACKER",
            "AGRO": "AGRO",
            "STOCK": "STOCK",
            "LONGHAUL": "LONGHAUL",
            "CLUSTER": "CLUSTER",
            "CARGOTIMETABLE": "CARGOTIMETABLE",
        }
    
    @schemas.classproperty
    def UNIVERSAL(cls):
        return cls("UNIVERSAL")
    
    @schemas.classproperty
    def ROUTING(cls):
        return cls("ROUTING")
    
    @schemas.classproperty
    def ACCOUNT(cls):
        return cls("ACCOUNT")
    
    @schemas.classproperty
    def ADMIN(cls):
        return cls("ADMIN")
    
    @schemas.classproperty
    def STUDIO(cls):
        return cls("STUDIO")
    
    @schemas.classproperty
    def PACKER(cls):
        return cls("PACKER")
    
    @schemas.classproperty
    def AGRO(cls):
        return cls("AGRO")
    
    @schemas.classproperty
    def STOCK(cls):
        return cls("STOCK")
    
    @schemas.classproperty
    def LONGHAUL(cls):
        return cls("LONGHAUL")
    
    @schemas.classproperty
    def CLUSTER(cls):
        return cls("CLUSTER")
    
    @schemas.classproperty
    def CARGOTIMETABLE(cls):
        return cls("CARGOTIMETABLE")
