VERSION_YEAR = 2023
VERSION_MONTH = int('01')
VERSION_DAY = int('16')
VERSION_HOUR = int('22')
VERSION_MINUTE = int('01')
MAJOR_VERSION = 1
MINOR_VERSION = 9
PATCH_VERSION = 202301162201
version_date = '2023/01/16 22:01'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
