
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-15T20:35:06+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "4bedd7afcb30ffd081712398e6c7673e7f3ffd12",
 "version": "0.0.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
