
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-18T16:59:18-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "b6cf2009b1f531d6b5e17a5c7516c646c579c782",
 "version": "0.9.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
